"""backlog_02_ahn5_maaiveld

Revision ID: d35c9f206327
Revises: ef6be05f904c
Create Date: 2026-03-15 16:43:45.765035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35c9f206327'
down_revision: Union[str, None] = 'ef6be05f904c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maaiveld_overrides', sa.Column('MVin_bron', sa.String(), nullable=True))
    op.add_column('maaiveld_overrides', sa.Column('MVuit_bron', sa.String(), nullable=True))
    op.add_column('maaiveld_overrides', sa.Column('MVin_ahn5_m', sa.Float(), nullable=True))
    op.add_column('maaiveld_overrides', sa.Column('MVuit_ahn5_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maaiveld_overrides', 'MVuit_ahn5_m')
    op.drop_column('maaiveld_overrides', 'MVin_ahn5_m')
    op.drop_column('maaiveld_overrides', 'MVuit_bron')
    op.drop_column('maaiveld_overrides', 'MVin_bron')
    # ### end Alembic commands ###
