"""qua3_sync_alle_modellen

Revision ID: daa8d4ecc255
Revises: b3c4d5e6f7a8
Create Date: 2026-03-23 10:29:14.920056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa8d4ecc255'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boormachines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('naam', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('lengte_m', sa.Float(), nullable=False),
    sa.Column('breedte_m', sa.Float(), nullable=False),
    sa.Column('trekkracht_ton', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('wachtwoord_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=True),
    sa.Column('laatst_ingelogd', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profiel_punten',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('boring_id', sa.String(), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.Column('afstand_m', sa.Float(), nullable=False),
    sa.Column('NAP_z', sa.Float(), nullable=False),
    sa.Column('Rv_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['boring_id'], ['boringen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boringen', sa.Column('machine_type', sa.String(), nullable=True))
    op.add_column('klic_leidingen', sa.Column('mogelijk_sleufloze', sa.Boolean(), nullable=True))
    op.add_column('klic_leidingen', sa.Column('diepte_bron', sa.String(), nullable=True))
    op.add_column('klic_leidingen', sa.Column('ev_verplicht', sa.Boolean(), nullable=True))
    op.add_column('klic_leidingen', sa.Column('ev_contactgegevens', sa.String(), nullable=True))
    op.add_column('klic_leidingen', sa.Column('label_tekst', sa.Text(), nullable=True))
    op.add_column('klic_leidingen', sa.Column('toelichting_tekst', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('klic_leidingen', 'toelichting_tekst')
    op.drop_column('klic_leidingen', 'label_tekst')
    op.drop_column('klic_leidingen', 'ev_contactgegevens')
    op.drop_column('klic_leidingen', 'ev_verplicht')
    op.drop_column('klic_leidingen', 'diepte_bron')
    op.drop_column('klic_leidingen', 'mogelijk_sleufloze')
    op.drop_column('boringen', 'machine_type')
    op.drop_table('profiel_punten')
    op.drop_table('users')
    op.drop_table('boormachines')
    # ### end Alembic commands ###
