"""backlog_01_klic_leidingen

Revision ID: ef6be05f904c
Revises: 
Create Date: 2026-03-15 13:47:01.189147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6be05f904c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klic_leidingen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('klic_upload_id', sa.String(), nullable=False),
    sa.Column('beheerder', sa.String(), nullable=True),
    sa.Column('leidingtype', sa.String(), nullable=True),
    sa.Column('thema', sa.String(), nullable=True),
    sa.Column('dxf_laag', sa.String(), nullable=True),
    sa.Column('geometrie_wkt', sa.Text(), nullable=True),
    sa.Column('diepte_m', sa.Float(), nullable=True),
    sa.Column('diepte_override_m', sa.Float(), nullable=True),
    sa.Column('sleufloze_techniek', sa.Boolean(), nullable=True),
    sa.Column('bron_pdf_url', sa.String(), nullable=True),
    sa.Column('imkl_feature_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['klic_upload_id'], ['klic_uploads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('klic_uploads', sa.Column('aantal_leidingen', sa.Integer(), nullable=True))
    op.add_column('klic_uploads', sa.Column('aantal_beheerders', sa.Integer(), nullable=True))
    op.add_column('klic_uploads', sa.Column('verwerk_fout', sa.String(), nullable=True))
    op.add_column('klic_uploads', sa.Column('verwerkt_op', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('klic_uploads', 'verwerkt_op')
    op.drop_column('klic_uploads', 'verwerk_fout')
    op.drop_column('klic_uploads', 'aantal_beheerders')
    op.drop_column('klic_uploads', 'aantal_leidingen')
    op.drop_table('klic_leidingen')
    # ### end Alembic commands ###
